echo "*************************************"
echo "                                     "
echo "Welcome To Library Management System."
echo "                                     "
echo "*************************************"